// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package repository

import (
	"context"
	"database/sql"
	"net"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, full_name, email, email_lookup_hash, password_hash, token_version, is_adult, role, privacy_notice_version, privacy_notice_accepted_at, privacy_acceptance_hash, crypto_key_version, status
) VALUES (
    $1, $2, pgp_sym_encrypt($3::text, $14::text), $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, full_name, email, email_lookup_hash, phone, phone_lookup_hash, password_hash, token_version, is_adult, role, privacy_notice_version, privacy_notice_accepted_at, privacy_acceptance_hash, crypto_key_version, status, age_up_attempts, created_at, updated_at, last_login_at, deleted_at, deletion_reason
`

type CreateUserParams struct {
	ID                      uuid.UUID `json:"id"`
	FullName                string    `json:"full_name"`
	Column3                 string    `json:"column_3"`
	EmailLookupHash         []byte    `json:"email_lookup_hash"`
	PasswordHash            string    `json:"password_hash"`
	TokenVersion            int32     `json:"token_version"`
	IsAdult                 bool      `json:"is_adult"`
	Role                    string    `json:"role"`
	PrivacyNoticeVersion    string    `json:"privacy_notice_version"`
	PrivacyNoticeAcceptedAt time.Time `json:"privacy_notice_accepted_at"`
	PrivacyAcceptanceHash   []byte    `json:"privacy_acceptance_hash"`
	CryptoKeyVersion        int16     `json:"crypto_key_version"`
	Status                  string    `json:"status"`
	EncryptionKey           string    `json:"encryption_key"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Column3,
		arg.EmailLookupHash,
		arg.PasswordHash,
		arg.TokenVersion,
		arg.IsAdult,
		arg.Role,
		arg.PrivacyNoticeVersion,
		arg.PrivacyNoticeAcceptedAt,
		arg.PrivacyAcceptanceHash,
		arg.CryptoKeyVersion,
		arg.Status,
		arg.EncryptionKey,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.EmailLookupHash,
		&i.Phone,
		&i.PhoneLookupHash,
		&i.PasswordHash,
		&i.TokenVersion,
		&i.IsAdult,
		&i.Role,
		&i.PrivacyNoticeVersion,
		&i.PrivacyNoticeAcceptedAt,
		&i.PrivacyAcceptanceHash,
		&i.CryptoKeyVersion,
		&i.Status,
		&i.AgeUpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.DeletionReason,
	)
	return i, err
}

const getLevelAttemptsByDate = `-- name: GetLevelAttemptsByDate :one
SELECT COUNT(*) as attempt_number 
FROM level_attempts 
WHERE user_id = $1 AND level_id = $2 AND attempt_date = $3
FOR UPDATE
`

type GetLevelAttemptsByDateParams struct {
	UserID      uuid.UUID `json:"user_id"`
	LevelID     uuid.UUID `json:"level_id"`
	AttemptDate time.Time `json:"attempt_date"`
}

func (q *Queries) GetLevelAttemptsByDate(ctx context.Context, arg GetLevelAttemptsByDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLevelAttemptsByDate, arg.UserID, arg.LevelID, arg.AttemptDate)
	var attempt_number int64
	err := row.Scan(&attempt_number)
	return attempt_number, err
}

const getUserByEmailHash = `-- name: GetUserByEmailHash :one
SELECT id, full_name, pgp_sym_decrypt(email::bytea, $2::text) as email, email_lookup_hash, phone, phone_lookup_hash, password_hash, token_version, is_adult, role, privacy_notice_version, privacy_notice_accepted_at, privacy_acceptance_hash, crypto_key_version, status, age_up_attempts, created_at, updated_at, last_login_at, deleted_at, deletion_reason 
FROM users
WHERE email_lookup_hash = $1 AND deleted_at IS NULL
`

type GetUserByEmailHashParams struct {
	EmailLookupHash []byte `json:"email_lookup_hash"`
	EncryptionKey   string `json:"encryption_key"`
}

type GetUserByEmailHashRow struct {
	ID                      uuid.UUID      `json:"id"`
	FullName                string         `json:"full_name"`
	Email                   string         `json:"email"`
	EmailLookupHash         []byte         `json:"email_lookup_hash"`
	Phone                   []byte         `json:"phone"`
	PhoneLookupHash         []byte         `json:"phone_lookup_hash"`
	PasswordHash            string         `json:"password_hash"`
	TokenVersion            int32          `json:"token_version"`
	IsAdult                 bool           `json:"is_adult"`
	Role                    string         `json:"role"`
	PrivacyNoticeVersion    string         `json:"privacy_notice_version"`
	PrivacyNoticeAcceptedAt time.Time      `json:"privacy_notice_accepted_at"`
	PrivacyAcceptanceHash   []byte         `json:"privacy_acceptance_hash"`
	CryptoKeyVersion        int16          `json:"crypto_key_version"`
	Status                  string         `json:"status"`
	AgeUpAttempts           int16          `json:"age_up_attempts"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	LastLoginAt             sql.NullTime   `json:"last_login_at"`
	DeletedAt               sql.NullTime   `json:"deleted_at"`
	DeletionReason          sql.NullString `json:"deletion_reason"`
}

func (q *Queries) GetUserByEmailHash(ctx context.Context, arg GetUserByEmailHashParams) (GetUserByEmailHashRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailHash, arg.EmailLookupHash, arg.EncryptionKey)
	var i GetUserByEmailHashRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.EmailLookupHash,
		&i.Phone,
		&i.PhoneLookupHash,
		&i.PasswordHash,
		&i.TokenVersion,
		&i.IsAdult,
		&i.Role,
		&i.PrivacyNoticeVersion,
		&i.PrivacyNoticeAcceptedAt,
		&i.PrivacyAcceptanceHash,
		&i.CryptoKeyVersion,
		&i.Status,
		&i.AgeUpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.DeletionReason,
	)
	return i, err
}

const insertExperienceHistory = `-- name: InsertExperienceHistory :exec
INSERT INTO experience_history (
    id, user_id, level_id, event_type, xp_gained, source, verification_method, sync_event_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertExperienceHistoryParams struct {
	ID                 uuid.UUID     `json:"id"`
	UserID             uuid.NullUUID `json:"user_id"`
	LevelID            uuid.UUID     `json:"level_id"`
	EventType          string        `json:"event_type"`
	XpGained           int32         `json:"xp_gained"`
	Source             string        `json:"source"`
	VerificationMethod string        `json:"verification_method"`
	SyncEventID        uuid.NullUUID `json:"sync_event_id"`
}

func (q *Queries) InsertExperienceHistory(ctx context.Context, arg InsertExperienceHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertExperienceHistory,
		arg.ID,
		arg.UserID,
		arg.LevelID,
		arg.EventType,
		arg.XpGained,
		arg.Source,
		arg.VerificationMethod,
		arg.SyncEventID,
	)
	return err
}

const insertLevelAttempt = `-- name: InsertLevelAttempt :exec
INSERT INTO level_attempts (
    id, user_id, level_id, attempt_date, attempt_number, xp_awarded, completed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertLevelAttemptParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	LevelID       uuid.UUID `json:"level_id"`
	AttemptDate   time.Time `json:"attempt_date"`
	AttemptNumber int32     `json:"attempt_number"`
	XpAwarded     int32     `json:"xp_awarded"`
	Completed     bool      `json:"completed"`
}

func (q *Queries) InsertLevelAttempt(ctx context.Context, arg InsertLevelAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertLevelAttempt,
		arg.ID,
		arg.UserID,
		arg.LevelID,
		arg.AttemptDate,
		arg.AttemptNumber,
		arg.XpAwarded,
		arg.Completed,
	)
	return err
}

const insertSyncEvent = `-- name: InsertSyncEvent :exec
INSERT INTO sync_events (
    id, device_id, user_id, payload_hash, hmac_signature, crypto_key_version, hmac_valid, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertSyncEventParams struct {
	ID               uuid.UUID `json:"id"`
	DeviceID         uuid.UUID `json:"device_id"`
	UserID           uuid.UUID `json:"user_id"`
	PayloadHash      []byte    `json:"payload_hash"`
	HmacSignature    []byte    `json:"hmac_signature"`
	CryptoKeyVersion int16     `json:"crypto_key_version"`
	HmacValid        bool      `json:"hmac_valid"`
	Status           string    `json:"status"`
}

func (q *Queries) InsertSyncEvent(ctx context.Context, arg InsertSyncEventParams) error {
	_, err := q.db.ExecContext(ctx, insertSyncEvent,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.PayloadHash,
		arg.HmacSignature,
		arg.CryptoKeyVersion,
		arg.HmacValid,
		arg.Status,
	)
	return err
}

const logAdminAudit = `-- name: LogAdminAudit :exec
INSERT INTO admin_audit_log (
    id, actor_user_id, action, entity_type, entity_id, before_state, after_state, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type LogAdminAuditParams struct {
	ID          uuid.UUID             `json:"id"`
	ActorUserID uuid.NullUUID         `json:"actor_user_id"`
	Action      string                `json:"action"`
	EntityType  string                `json:"entity_type"`
	EntityID    uuid.NullUUID         `json:"entity_id"`
	BeforeState pqtype.NullRawMessage `json:"before_state"`
	AfterState  pqtype.NullRawMessage `json:"after_state"`
	IpAddress   net.IP                `json:"ip_address"`
	UserAgent   string                `json:"user_agent"`
}

func (q *Queries) LogAdminAudit(ctx context.Context, arg LogAdminAuditParams) error {
	_, err := q.db.ExecContext(ctx, logAdminAudit,
		arg.ID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeState,
		arg.AfterState,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const updateSyncEventStatus = `-- name: UpdateSyncEventStatus :exec
UPDATE sync_events SET status = $2, processed_at = NOW() WHERE id = $1
`

type UpdateSyncEventStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSyncEventStatus(ctx context.Context, arg UpdateSyncEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncEventStatus, arg.ID, arg.Status)
	return err
}

const upsertDailyStreak = `-- name: UpsertDailyStreak :exec
INSERT INTO daily_streak (
    user_id, activity_date
) VALUES (
    $1, $2
) ON CONFLICT (user_id, activity_date) DO NOTHING
`

type UpsertDailyStreakParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ActivityDate time.Time `json:"activity_date"`
}

func (q *Queries) UpsertDailyStreak(ctx context.Context, arg UpsertDailyStreakParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyStreak, arg.UserID, arg.ActivityDate)
	return err
}

const upsertPlayerProgress = `-- name: UpsertPlayerProgress :exec
INSERT INTO player_progress (
    user_id, level_id, best_score, xp_total_for_level, attempts_count, first_completed_at, last_completed_at
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
) ON CONFLICT (user_id, level_id) DO UPDATE SET
    best_score = GREATEST(player_progress.best_score, EXCLUDED.best_score),
    xp_total_for_level = player_progress.xp_total_for_level + EXCLUDED.xp_total_for_level,
    attempts_count = player_progress.attempts_count + 1,
    last_completed_at = NOW()
`

type UpsertPlayerProgressParams struct {
	UserID          uuid.UUID `json:"user_id"`
	LevelID         uuid.UUID `json:"level_id"`
	BestScore       int32     `json:"best_score"`
	XpTotalForLevel int32     `json:"xp_total_for_level"`
	AttemptsCount   int32     `json:"attempts_count"`
}

func (q *Queries) UpsertPlayerProgress(ctx context.Context, arg UpsertPlayerProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerProgress,
		arg.UserID,
		arg.LevelID,
		arg.BestScore,
		arg.XpTotalForLevel,
		arg.AttemptsCount,
	)
	return err
}
