// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetLevelAttemptsByDate(ctx context.Context, arg GetLevelAttemptsByDateParams) (int64, error)
	GetUserByEmailHash(ctx context.Context, emailLookupHash []byte) (User, error)
	InsertExperienceHistory(ctx context.Context, arg InsertExperienceHistoryParams) error
	InsertLevelAttempt(ctx context.Context, arg InsertLevelAttemptParams) error
	InsertSyncEvent(ctx context.Context, arg InsertSyncEventParams) error
	LogAdminAudit(ctx context.Context, arg LogAdminAuditParams) error
	UpdateSyncEventStatus(ctx context.Context, arg UpdateSyncEventStatusParams) error
	UpsertDailyStreak(ctx context.Context, arg UpsertDailyStreakParams) error
	UpsertPlayerProgress(ctx context.Context, arg UpsertPlayerProgressParams) error
}

var _ Querier = (*Queries)(nil)
